apiVersion: apps/v1
kind: Deployment

metadata:
  name: mecaniqa-java

spec:
  replicas: 1

  selector:
    matchLabels:
      app: mecaniqa-java

  template:
    metadata:
      labels:
        app: mecaniqa-java

    spec:
      containers:
        - name: mecaniqa-java
          image: mecaniqa-boa-vista-java:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
