apiVersion: apps/v1
kind: Deployment

metadata:
  name: mecaniqa-mysql

spec:
  replicas: 1

  selector:
    matchLabels:
      app: mecaniqa-mysql

  template:
    metadata:
      labels:
        app: mecaniqa-mysql

    spec:
      containers:
        - name: mecaniqa-mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: mecaniqa